version: '3'
services:
  lavagna:
    build: .
    environment:
     - DB_DIALECT=MYSQL
     - DB_URL=jdbc:mysql://mysql:3306/lavagna?useSSL=false
     - DB_USER=root
     - DB_PASS=root_password
     - SPRING_PROFILE=dev
    expose:
      - 8080
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
    expose:
      - 3306
    volumes:
      - ./db_setup/init:/docker-entrypoint-initdb.d
      - ./db_setup/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
       - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
       - ./src/main/webapp:/usr/share/nginx/html/webapp
    depends_on:
      - lavagna  
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - 8081:80
    networks:
      - docs-net

    

networks:
  docs-net:
